# Generated by Django 3.2.3 on 2021-05-26 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbbeneficiarios',
            name='userApp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='userApp'),
        ),
    ]
