# Generated by Django 3.2.3 on 2021-05-26 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Suppliers', '0002_alter_tbbeneficiarios_userapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbbeneficiarios',
            name='userApp',
        ),
        migrations.AddField(
            model_name='tbbeneficiarios',
            name='useradm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='UserAdm'),
            preserve_default=False,
        ),
    ]
